SourceS/Controllers/DueñosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SourceS.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using SourceS.Models.Usuarios;
using SourceS.Models.ViewModels;
using SourceS.Models.ViewModels.ApagadoDevice;

namespace SourceS.Controllers
{
    public class DueñosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        #region Administrador
        // GET: Dueños
        [Authorize(Roles = ("Administrador,Admin"))]
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return HttpNotFound();
            }
            var usuarios =  await db.Administradores.AsNoTracking().Where(a => a.personaID == userId).SelectMany(d => d.Dueños)
                .OrderBy(n => n.Nombre).ToListAsync();

            return View(usuarios);
        }
        // GET: Dueños/Create

        [Authorize(Roles = ("Administrador"))]
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        // POST: Dueños/Create
        [HttpPost]
        [Authorize(Roles = ("Administrador"))]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel registro)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = registro.Email, Email = registro.Email, EmailConfirmed = true, PhoneNumber = registro.celular };
                var result = await UserManager.CreateAsync(user, registro.Password);
                var userId = User.Identity.GetUserId();


                //Create ApplicationUser
                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id, "Usuario");
                    var dueño = new Dueño();
                    dueño.personaID = user.Id;
                    dueño.ApplicationUser = db.Users.Find(user.Id);
                    dueño.Nombre = registro.nombre;
                    dueño.ApellidoPaterno = registro.apellidoPaterno;
                    dueño.ApellidoMaterno = registro.apellidoMaterno;
                    dueño.Celular = registro.celular;
                    dueño.Gasolineras = new List<Gasolinera>();


                    // TODO: Add insert logic here
                    db.Dueños.Add(dueño);
                    //Add to Admin Role
                    var administrador = db.Administradores.Find(userId);
                    administrador.Dueños.Add(dueño);

                    db.SaveChanges();
                    return Json(new {success = true});
                }

                AddErrors(result);
            }

            return PartialView("_Create",registro);

        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        // GET: Dueños/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dueño dueño = db.Dueños.Find(); ;
            if (dueño == null)
            {
                return HttpNotFound();
            }
            return View(dueño);
        }


        // GET: Dueños/Edit/5
        [Authorize(Roles = ("Administrador"))]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dueño dueño = db.Dueños.Find(id);
            if (dueño == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit",dueño);
        }

        // POST: Dueños/Edit/5
        [Authorize(Roles = ("Administrador"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Dueño dueño)
        {
            var administrador = db.Administradores.AsNoTracking().Include(d => d.Dueños).FirstOrDefault(a => a.personaID == dueño.AdministradorId);        
            //One to Many
            var user = await UserManager.FindByIdAsync(dueño.personaID);
         
            user.Email = dueño.ApplicationUser.Email;
            user.UserName = dueño.ApplicationUser.Email;
            await UserManager.UpdateAsync(user);
            dueño.ApplicationUser.Id = user.Id;
            dueño.ApplicationUser = db.Users.Find(user.Id);
            dueño.Administrador = administrador;

            if (ModelState.IsValid)
            {
                db.Entry(dueño).State = EntityState.Modified;
                AddedUsuario(dueño.personaID,administrador);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("_Edit", dueño);
        }

        public void AddedUsuario(string usuarioId, Administrador administrador)
        {
            var usuarios = new HashSet<string>(administrador.Dueños.Select(d => d.personaID));

            foreach (var usuario in db.Dueños.AsNoTracking())
            {
                if (usuario.personaID == usuarioId)
                {

                    if (usuarios.Contains(usuario.personaID))
                    {
                        administrador.Dueños.Remove(usuario);
                    }

                    if (usuarios.Contains(usuario.personaID))
                    {
                        administrador.Dueños.Add(usuario);
                    }
                }
            }

        }


        // GET: Dueños/Delete/5
        [Authorize(Roles = ("Administrador"))]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dueño dueño = db.Dueños.Find(id);
            if (dueño == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete",dueño);
        }

        // POST: Dueños/Delete/5
        [Authorize(Roles = ("Administrador"))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {      
            var dueño = await  db.Dueños.FirstOrDefaultAsync(d => d.personaID == id);
            db.Dueños.Attach(dueño);
            db.Dueños.Remove(dueño);

            var user = db.Users.AsNoTracking().FirstOrDefault(X => X.Id == id);
            db.Users.Attach(user);
            db.Users.Remove(user);
            db.SaveChanges();

            /* if (dueño.Gasolineras != null && dueño.Gasolineras.Any())
             {
                 DeleteGasolineras(dueño.Gasolineras.ToList(), dueño);
             }
             db.Dueños.Remove(dueño);*/
            try
            {
                db.SaveChanges();
                return Json(new {success = true});

            } catch(Exception E)
            {
                Console.WriteLine(E);
            }
            return PartialView("_Delete", dueño);
        }

        public void DeleteGasolineras(List<Gasolinera> gasolineras,Dueño dueño)
        {
            foreach (var gasolinera in gasolineras)
            {
                if (dueño.Gasolineras.Contains(gasolinera))
                {
                    dueño.Gasolineras.Remove(gasolinera);
                }
            }
        }


        public JsonResult _ControlOFF(string usuarioId)
        {
            //Deshabilitar al Administrador -> Apagar Todos lo Usuarios del Admin
            var usuario = db.Dueños.Find(usuarioId);
            usuario.Activado = true;
            db.Dueños.Attach(usuario);
            db.Entry(usuario).State = EntityState.Modified;
            //OFF Gasolineras
            db.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult _ControlON(string usuarioId)
        {
            //Deshabilitar al Administrador -> Apagar Todos lo Usuarios del Admin
            var usuario = db.Dueños.Find(usuarioId);
            usuario.Activado = false;
            db.Dueños.Attach(usuario);
            db.Entry(usuario).State = EntityState.Modified;
            //OFF Gasolineras
            db.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Apagado(string id)
        {
            var Dueño = db.Dueños.Find(id);
            if (Dueño.Activado == true)
            {
                //*Logica para desactivar apagado
                //Modified Dueño
                Dueño.Activado = false;
                //Dispositivos del Cliente
                if (ModelState.IsValid)
                {
                    var conexion = new ClientSocket();
                    var devices = Dueño.Gasolineras.SelectMany(d => d.Dispositivos);
                    foreach (var dispositivo in devices)
                    {
                        var historico = new ProgramaDto();
                        {
                            historico.ip = dispositivo.ip;
                            historico.identificador = 0;
                            historico.fecha = DateTime.Now.ToString("MM/dd/yyyy");

SourceS/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        @DateTime.Now
    </div>
    <div>
        <strong>Copyright</strong> &copy; @DateTime.Now.Year
    </div>
</div>

SourceS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <!-- Add local styles, mostly for plugins css file -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href="~/Content/plugins/footable/footable.core.css" rel="stylesheet">
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <!-- <link href="@Url.Content("~/Content/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css")" rel="stylesheet" type="text/css" />-->
    <link href="~/Content/plugins/datapicker/datepicker3.css" rel="stylesheet" />
    <!-- Special Render -->
    @RenderSection("head_scripts", required: false)
    @Styles.Render("~/plugins/fullCalendarStyles")
    <!-- Primary Inspinia style -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/Content/plugins/dropzone/dropZoneStyles")
    @Styles.Render("~/Content/plugins/FileInput/css")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/laddaStyles")
    @Styles.Render("~/plugins/footableStyles")


</head>
<body class="top-navigation">
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>


    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/fullCalendar")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/chosenJs")
    @Scripts.Render("~/plugins/dropZone")
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/clockpicker")
    @Scripts.Render("~/plugins/ladda")
    @Scripts.Render("~/Content/plugins/FileInput/js")
    @Scripts.Render("~/plugins/nestable")
    @Scripts.Render("~/plugins/footable")
    @Scripts.Render("~/plugins/masonry")
    @Scripts.Render("~/plugins/select2")
    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/plugins/daterangepicker/daterangepicker.js"></script>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

<script>
    $(document).ready(function () {

        $('input[name="daterange"]').daterangepicker();

        $('#data_1 .input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });

        $('#data_5 .input-daterange').datepicker({
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });
        $(".table-dashboard").footable();

    });
</script>

</body>
</html>

SourceS/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">Gas Station Web</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            { 

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Administradores", "Index", "Administradores")</li>
              
                </ul>
                @Html.Partial("_LoginPartial")
            }
            
            @if (Request.IsAuthenticated && User.IsInRole("Administrador"))
            {

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Usuarios", "Index", "Dueños")</li>
                </ul>

                @Html.Partial("_LoginPartial")
            }

            @if (Request.IsAuthenticated && User.IsInRole("Usuario"))
            {

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Historiales", "Usuario", "Home")</li>
                    <li>@Html.ActionLink("Estaciones", "Index", "Gasolineras")</li>
                </ul>

                @Html.Partial("_LoginPartial")
            }

        </div>
    </nav>
</div>