SourceS/Models/ViewModels/GasolinerasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SourceS.Models.ViewModels
{
    public class GasolinerasViewModel
    {
        public Gasolinera Gasolinera { get; set; }
        public ICollection<Dispositivo> Dispositivos { get; set; }
        public int[] productosID { get; set; }
    }
}

SourceS/Controllers/DispositivosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SourceS.Models;
using SourceS.Models.ViewModels;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace SourceS.Controllers
{
    public class DispositivosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Dispositivos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dispositivo dispositivo = db.Dispositivos.Find(id);
            if (dispositivo == null)
            {
                return HttpNotFound();
            }
            return View(dispositivo);
        }


        // GET: Dispositivos/Edit/5
        [Authorize(Roles = ("Administrador"))]
        public ActionResult Edit(int? id)
        { 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dispositivo dispositivo = db.Dispositivos.Find(id);
            if (dispositivo == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit",dispositivo);
        }

        // POST: Dispositivos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ("Administrador"))]
        public ActionResult Edit([Bind(Include = "dispositivoID,ip,nombre,gasolineraID")] Dispositivo dispositivo)
        {
            if (ModelState.IsValid)
            {
                dispositivo.Gasolinera = db.Gasolineras.Find(dispositivo.gasolineraID);
                db.Entry(dispositivo).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new {success = true});
            }
            return PartialView("_Edit",dispositivo);
        }

        // GET: Dispositivos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dispositivo dispositivo = db.Dispositivos.Find(id);
            if (dispositivo == null)
            {
                return HttpNotFound();
            }
            return View(dispositivo);
        }

        // POST: Dispositivos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idGasolinera)
        {
            Dispositivo dispositivo = db.Dispositivos.Find(id);
            var gasolinera = db.Gasolineras.Find(idGasolinera);
            if (gasolinera.Dispositivos.Any())
            {
                if (gasolinera.Dispositivos.Contains(dispositivo))
                {
                    gasolinera.Dispositivos.Remove(dispositivo);
                }

            }
            db.Dispositivos.Remove(dispositivo);
            db.SaveChanges();
            return RedirectToAction("Delete", new { id = idGasolinera });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SourceS/Controllers/GasolinerasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SourceS.Models;
using SourceS.Models.ViewModels;
using System.Data.Entity.Infrastructure;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using SourceS.Helpers;
using SourceS.Models.FormularioAdministrador;

namespace SourceS.Controllers
{
    public class GasolinerasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        #region Admin
        // GET: Gasolineras
        [Authorize(Roles=("Usuario"))]
        public ActionResult Index()
        {

            var usuarioId = User.Identity.GetUserId();
            if (usuarioId == null)
            {
                return HttpNotFound();
            }
            var dueño = db.Dueños.Find(usuarioId);
            if (dueño == null)
            {
                return HttpNotFound();
            }

            var gasolineras =dueño.Gasolineras.ToList();
            ViewBag.userName = dueño.Nombre;

            return View(gasolineras);
        }

        [Authorize(Roles = ("Administrador"))]
        public async Task<ActionResult> Lista(string id)
        {

            if (String.IsNullOrEmpty(id)) { return new HttpStatusCodeResult(404); }

            var viewModel = new List<DueñoGasolinerasVM>();
            var persona = await db.Dueños.Where(x => x.personaID == id).Include(t => t.Gasolineras).FirstOrDefaultAsync();

            ViewBag.personaID = persona.personaID;
            ViewBag.Nombre = persona.Nombre;

            return View(viewModel);
        }

        public JsonResult getData(string id)
        {
            var viewModels = new List<DueñoGasolinerasVM>();

            var gasolineraViewModel = db.Dueños.AsQueryable().Where(x => x.personaID == id).Include(t => t.Gasolineras)
                .SelectMany(g => g.Gasolineras);

            foreach (var model in gasolineraViewModel)
            {
                var dispositivos = model.Dispositivos.Select(d => new Dispositivo { dispositivoID = d.dispositivoID, ip = d.ip, nombre = d.nombre, gasolineraID = d.gasolineraID });
                viewModels.Add(new DueñoGasolinerasVM
                {
                    gasolineraID = model.gasolineraID,
                    identificador = model.identificador,
                    estado = model.estado,
                    municipio = model.municipio,
                    calle = model.calle,
                    Dispositivos = dispositivos.ToList()

                });

            }

            if (gasolineraViewModel != null)
            {

                return Json(new { data = viewModels }, JsonRequestBehavior.AllowGet);

            }
            return Json(new { data = "" }, JsonRequestBehavior.AllowGet);

        }

        #region Crear Gasolinera
        public ActionResult Formulario(string usuarioId)
        {
            var opt = Option(1);
            ViewBag.Opt = opt;
            ViewBag.usuarioIDE = usuarioId;
            return View();
        }

        public MultipleStepProgressTabOption Option(int currentIndex)
        {
            var opt = new MultipleStepProgressTabOption()

            {

                Steps = new List<string>()

                {

                    "Crear Gasolinera",

                    "Crear Dispositivo",

                    "Crear Producto"

                },

                CurrentStepIndex = currentIndex

            };

            return opt;
        }

        [HttpPost]
        [Authorize(Roles = ("Administrador"))]
        public ActionResult Step1(string usuarioId, Gasolinera gasolinera)
        {
            gasolinera.identificador = GenerateRandomNo(gasolinera.estado, gasolinera.municipio, gasolinera.colonia, gasolinera.calle);
            var dueño = db.Dueños.Find(usuarioId);

            if (ModelState.IsValid)
            {
                var opt = Option(2);
                ViewBag.Opt = opt;
                ViewBag.gasolineraID = new SelectList(db.Gasolineras.Where(x => x.gasolineraID == gasolinera.gasolineraID), "gasolineraID", "identificador");
                db.Gasolineras.Add(gasolinera);
                dueño.Gasolineras.Add(gasolinera);

                db.SaveChanges();
                return PartialView("_Step2");
            }

            var opt1 = Option(1);
            ViewBag.Opt = opt1;

            return PartialView("Formulario", gasolinera);
        }

        [HttpPost]
        [Authorize(Roles = ("Administrador"))]
        public ActionResult Step2(DispositivoDTO dispositivo,int gasolineraID,CantidadProductos CantidadProductos)
        {
            var gasolinera = db.Gasolineras.Find(gasolineraID);
            if (gasolinera != null)
            {
                if (ModelState.IsValid)
                {

                    var device = new Dispositivo()
                    {
                        ip = dispositivo.ip,
                        nombre = dispositivo.nombre,
                        Gasolinera = gasolinera,
                        gasolineraID = gasolineraID,
                    };

                    var opt = Option(3);
                    ViewBag.Opt = opt;
                    db.Dispositivos.Add(device);
                    gasolinera.Dispositivos.Add(device);
                    db.SaveChanges();
                    //Enum Cantidad Productos
                    var lista = GetProductos(CantidadProductos);
                    ViewBag.idGasolinera = gasolineraID;
                    //Model Lista productos
                    return PartialView("_Step3",lista);
                }
            }

            //Ocurs Error
            var opt1 = Option(2);
            ViewBag.Opt = opt1;
            ViewBag.gasolineraID = new SelectList(db.Gasolineras.Where(x => x.gasolineraID == gasolinera.gasolineraID), "gasolineraID", "identificador");
            return PartialView("_Step2", dispositivo);
        }

        public IList<Producto> GetProductos(CantidadProductos enumerable)
        {
            var producto = new List<Producto>();
            var productos = new List<Producto>();
            if (enumerable == CantidadProductos.Uno)
            {
                producto = new List<Producto>()
            {
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "A",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date}
            };
                productos.AddRange(producto);
            }
            if (enumerable == CantidadProductos.Dos)
            {
                producto = new List<Producto>()
            {
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "A",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                 new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "B",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date}
            };
                productos.AddRange(producto);
            }
            if (enumerable == CantidadProductos.Tres)
            {
                producto = new List<Producto>()
            {
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "A",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                 new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "B",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "C",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date}
            };
                productos.AddRange(producto);
            }
            if (enumerable == CantidadProductos.Cuatro)
            {
                producto = new List<Producto>()
            {
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "A",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                 new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "B",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "C",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                 new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "D",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date}
            };
                productos.AddRange(producto);
            }
            if (enumerable == CantidadProductos.Cinco)
            {
                producto = new List<Producto>()
            {
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "A",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                 new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "B",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                new Producto() {
                Nombre = "Producto",
                Precio = "10.00",
                Letra = "C",
                IsDeleted  = false,
                RowVersion = DateTime.Now.Date},
                 new Producto() {

SourceS/Controllers/ProductosController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using SourceS.Models;

namespace SourceS.Controllers
{
    [Authorize(Roles =("Admin,Administrador"))]
    public class ProductosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "productoID,Nombre,Moonto,RowVersion")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Productos.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(producto);
        }


        // GET: Productos/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id,string Andromeda)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            

            Producto producto = db.Productos.Find(id);
            ViewBag.Androide = Andromeda;
            if (producto == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit",producto);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "productoID,Nombre,Precio,RowVersion,GasolineraId,Letra")] Producto producto,string Andromeda)
        {
            if (ModelState.IsValid)
            {
                producto.Gasolinera = db.Gasolineras.Find(producto.GasolineraId);

                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();

                return Json(new {success = true });
            }
            return PartialView("_Edit",producto);
        }


        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productos.Find(id);
            db.Productos.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Delete");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SourceS/Views/Gasolineras/Details.cshtml
@model SourceS.Models.Gasolinera

@{
    ViewBag.Title = "Details";
}

<div id="detailsModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="detailsModalContent"></div>
        </div>
    </div>
</div>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Detalles</h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Gasolinera: </strong>
            </li>
            <li>
                @Html.ActionLink("Regresar a la Lista de usuarios", "Lista","Gasolineras", new { id = ViewBag.Androide },null)
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>

                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">

                                <div class="col-lg-4">
                                    <div class="widget-head-color-box p-lg text-center">
                                        <!--Name-->
                                        <div class="m-b-md">
                                            <h2 class="font-bold no-margins">
                                                @Model.identificador
                                            </h2>
                                        </div>
                                        <img src="@Url.Content("~/Images/gas-station.jpg")" class="img-circle circle-border m-b-md" alt="profile">
                                        <div>
                                            <span>Estado :</span>
                                            <span>@Model.estado</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-8">
                                    <div class="row m-t-sm">
                                        <div class="col-lg-12">
                                            <div class="panel blank-panel">
                                                <div class="panel-heading">
                                                    <div class="panel-options">
                                                        <ul class="nav nav-tabs">
                                                            <li class="active"><a href="#tab-1" data-toggle="tab"><i class="fa fa-info"></i> Detalle Gasolinera</a></li>
                                                            <li class=""><a href="#tab-2" data-toggle="tab"><i class="fa fa-info"></i> Dispositivo</a></li>
                                                            <li class=""><a href="#tab-3" data-toggle="tab"><i class="fa fa-info"></i> Productos</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div class="panel-body">
                                                    <div class="tab-content">
                                                        <div class="tab-pane active" id="tab-1">
                                                            <div class="">
                                                                <div class="col-md-6">
                                                                    <dl>
                                                                        <dt>Identificador</dt>
                                                                        <dd>@Model.identificador</dd>
                                                                        <dt>Dueño</dt>
                                                                        <dd>@Model.Dueño.Nombre</dd>
                                                                        <dt>Estado:</dt>
                                                                        <dd>@Model.estado</dd>
                                                                        <dt>Municipio:</dt>
                                                                        <dd>  @Model.municipio</dd>
                                                                        <dt>Calle:</dt>
                                                                        <dd>@Model.calle </dd>
                                                                    </dl>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="tab-pane" id="tab-2">
                                                            <div class="col-md-6">
                                                                <h2>Detalle Dispositivo</h2>
                                                                <hr>
                                                                <div class="widget-head-color-box p-lg text-center">

                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                @foreach (var item in Model.Dispositivos)
                                                                {
                                                                    <dl>
                                                                        <dt>IP: @item.ip</dt>
                                                                        <dt>
                                                                            Nombre:@item.nombre  @Html.ActionLink("Editar", "Edit", "Dispositivos",
                                                                                new { id = item.dispositivoID },
                                                                                new { @class = "btn btn-default", data_modal = "details" })
                                                                        </dt>
                                                                    </dl>
                                                                }
                                                            </div>
                                                        </div>
                                                        <div class="tab-pane" id="tab-3">
                                                            <div class="">
                                                                <div class="col-md-6">
                                                                    @foreach (var itemModel in Model.Productos)
                                                                    {
                                                                        <div class="row">
                                                                            <div class="col-xs-6">
                                                                                <p>Nombre: @itemModel.Nombre</p>
                                                                                <p>Precio: $ @itemModel.Precio</p>
                                                                                <p> Creado el: @itemModel.RowVersion</p>
                                                                            </div>
                                                                            <div class="col-xs-6">
                                                                                @Html.ActionLink("Editar", "Edit", "Productos",
                                                                                    new {id = itemModel.ProductoId, Andromeda = ViewBag.Androide},
                                                                                    new {@class = "btn btn-default", data_modal = "details"})
                                                                            </div>
                                                                        </div>
                                                                        
                                                                    }
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/plugins/bootstrap")
    <script src="~/Scripts/app/workModal.js"></script>
}

SourceS/Views/Gasolineras/_Delete.cshtml
@model SourceS.Models.Gasolinera

@{
    ViewBag.Title = "Delete";
    var valor = ViewBag.idPersona;
}

<div class="modal-header" style="background:#c94c4c; color: white;">
    <button id="btn" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Gasolinera</h4>
</div>



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5></h5>
                </div>
                <div class="ibox-content">
                    <div class="modal-body">
                        <h3>¿Esta seguro de eliminar la gasolinera del Dueño?</h3>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.identificador)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.identificador)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ciudad)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ciudad)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.municipio)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.municipio)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.estado)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.estado)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.colonia)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.colonia)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.calle)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.calle)
                            </dd>

                        </dl>
                        @using (Ajax.BeginForm("Delete", "Gasolineras", new { id = Model.gasolineraID, Andromeda = ViewBag.idPersona }, new AjaxOptions { InsertionMode = InsertionMode.Replace, OnSuccess = "getResult" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Eliminar" class="btn btn-warning btn-block" />
                            </div>
                        }



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal-footer">
    <div class="form-group">
        <button type="button" class="btn" data-dismiss="modal">Regresar</button>
    </div>
</div>